// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Persistence.API.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Microservice.Persistence.API.Data.Context
{
    public partial class MicroserviceEFCoreContext : DbContext
    {
        public MicroserviceEFCoreContext()
        {
        }

        public MicroserviceEFCoreContext(DbContextOptions<MicroserviceEFCoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<OrdenItem> OrdenItems { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Orden>(entity =>
            {
                entity.ToTable("Orden");

                entity.Property(e => e.Descripcion)
                    .HasMaxLength(250)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<OrdenItem>(entity =>
            {
                entity.ToTable("OrdenItem");

                entity.HasOne(d => d.Orden)
                    .WithMany(p => p.OrdenItems)
                    .HasForeignKey(d => d.OrdenId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_OrdernItemOrden");

                entity.HasOne(d => d.Producto)
                    .WithMany(p => p.OrdenItems)
                    .HasForeignKey(d => d.ProductoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_OrdernItemProducto");
            });

            modelBuilder.Entity<Producto>(entity =>
            {
                entity.ToTable("Producto");

                entity.Property(e => e.Descripcion)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Precio).HasColumnType("decimal(30, 6)");

                entity.Property(e => e.Unidad)
                    .HasMaxLength(3)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}